on:
  push:
    branches:
      - master 





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Befor' 
        run: ls

      - uses: actions/checkout@v3

      - name: 'After' 
        run: ls



      


